TF_SUB_ID        = "<<svc_ppl_gen_SUB_ID>>"
TF_CLIENT_ID     = "<<svc_ppl_gen_CLIENT_ID>>"
TF_CLIENT_SECRET = "<<svc_ppl_gen_CLIENT_SECRET>>"
TF_TENANT_ID     = "<<svc_ppl_gen_TENANT_ID>>"
PREFIX           = "sp"
BASE_NAME        =  "autogenerated"
NUMBER_TO_GENERATE = 5000
