variable "TF_SUB_ID" {
  type        = string
  description = "The Subscription ID for the Terrafrom Service Principal to build resources in. This is only used by the parent main.tf"
}

variable "TF_TENANT_ID" {
  type        = string
  description = "This is the tenant ID of the Azure subscription. This is only used by the parent main.tf"
}

variable "TF_CLIENT_ID" {
  type        = string
  description = "The Client ID(AppID) of the Service Principal that TF will use to Authenticate and build resources as. This account should have at least Contributor Role on the subscription. This is only used by the parent main.tf"

}
variable "TF_CLIENT_SECRET" {
  type        = string
  description = "The Client Secret of the Service Principal that TF will use to Authenticate and build resources as. This account should have at least Contributor Role on the subscription. This is only used by the parent main.tf"
}

variable "PREFIX" {
  type        = string
  description = "The prefix given to all Service Principal entities"
  default     = "sp"
}

variable "BASE_NAME" {
  type        = string
  description = "The main name given to all SP entities"
  default     = "autogenerated"
}


variable "NUMBER_TO_GENERATE" {
  type        = string
  description = "configurable number of Service Principal entities to generate"
  default     = 10
}
