#!/bin/bash
set -m
prefix=gortega
base_name=autogeneratedsbash

spToDeletestr=$(az ad sp list --query "[?appDisplayName != null] | [?starts_with(appDisplayName, '${prefix}-${base_name}-sp-' )].objectId" --all)

spToDeletestr=$(eval echo $spToDeletestr)
spToDeletestr=${spToDeletestr//"["/""}
spToDeletestr=${spToDeletestr//"]"/""}
spToDeletestr=${spToDeletestr//","/""}

spToDeletearray=($spToDeletestr)

for objectId in "${spToDeletearray[@]}";
do
# echo $objectId
az ad sp delete --id $objectId > /dev/null & 
sleep .2
done

fg

