#!/bin/bash
set -m
prefix=gortega
base_name=autogeneratedsbash


for i in {1..17000};
do
echo "$i"
az ad sp create-for-rbac -n http://${prefix}-${base_name}-sp-"$i" --skip-assignment > /dev/null & 
sleep .2
done

fg

