#!/bin/bash
set -m
prefix=gortega
base_name=autogeneratedsbash


for i in {1..100};
do
echo "$i"
az ad sp create-for-rbac -n http://${prefix}-${base_name}-sp-"$i" --skip-assignment > /dev/null & 
sleep .1
done

fg

