#!/bin/pwsh

Write-Host $PSVersionTable.OS

# Check version table for the OS.  Null is Windows, Otherwise Linux/Mac
if ($($PSVersionTable.OS) -eq $null) {
    Write-Host "Running hook using powershell.exe"
    c:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe -ExecutionPolicy Unrestricted -Command .github/hooks/mermaid-hook.ps1 -verbose
} else {
  Write-Host "Running hook using pwsh"
  pwsh .github/hooks/mermaid-hook.ps1 -verbose
}
