#!/bin/pwsh

if ($PSVersionTable.OS -eq $null) {
    c:/Windows/System32/WindowsPowerShell/v1.0/powershell.exe -ExecutionPolicy Unrestricted -Command $PSScriptRoot/mermaid-hook.ps1 -verbose
} else {
  pwsh $PSScriptRoot/mermaid-hook.ps1
}
