# File: .github/workflows/workflow.yml
name: AzureCLIAppConfigSettings

on: [push]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      # RG/FUNCTION APP INFO
      RESOURCE_GROUP_NAME: serviceprincipal-rg-dev
      FUNCTION_APP_NAME: sp-funcn-dev

      # CONFIG SETTINGS
      KEYVAULT_NAME: sp-kv-dev

    steps:    
    - name: Azure Login
      # uses: azure/login@v1
      # with:
      #   creds: ${{ secrets.AZURE_CREDENTIALS }}
      run: |
        # login to Azure
        az login --service-principal -u ${{ secrets.SERVICE_PRINCIPAL }} --tenant ${{ secrets.TENANT }} -p ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az account show
          az storage -h
          echo ${{ env.KEYVAULT_NAME }}
          az functionapp config appsettings set --name ${{ env.FUNCTION_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
            --settings KEYVAULT_NAME=${{ env.KEYVAULT_NAME }}