name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: dotnet tool install -g dotnet-format
    - name: Run ESLint
      run: dotnet-format --folder --check 