name: Docker CI

on:
  push:
    branches:
      - main

    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'spikes/**' # Don't build the spikes unless explicitly specified

    tags:
      - v*
  
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
      - main

    paths-ignore:
    - 'docs/**'
    - '**.md'
    - 'spikes/**' # Don't build the spikes unless explicitly specified

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      RESOURCE_GROUP: rg-svcprincipal-cse-dev-app

    steps:
    - name: Azure Login
      run: |
        # login to Azure
        az login --service-principal -u ${{ secrets.SERVICE_PRINCIPAL_ID }} --tenant ${{ secrets.TENANT_ID }} -p ${{ secrets.SERVICE_PRINCIPAL_SECRET }}

    - name: Get Resources
      run: |
        export FN_NAME=$(az resource list -g ${RESOURCE_GROUP} --resource-type Microsoft.Web/sites --query '[].name' -o tsv)
        export KV_NAME=$(az resource list -g ${RESOURCE_GROUP} --resource-type Microsoft.KeyVault/vaults --query '[].name' -o tsv)
        export DB_NAME=$(az resource list -g ${RESOURCE_GROUP} --resource-type Microsoft.DocumentDB/databaseAccounts --query '[].name' -o tsv)
        export ACR_NAME=$(az resource list -g ${RESOURCE_GROUP} --resource-type Microsoft.ContainerRegistry/registries --query '[].name' -o tsv)
        export STORAGE_NAME=$(az resource list -g ${RESOURCE_GROUP} --resource-type Microsoft.Storage/storageAccounts --query '[].name' -o tsv)
        echo "FN_NAME=${FN_NAME}" >> $GITHUB_ENV
        echo "KV_NAME=${KV_NAME}" >> $GITHUB_ENV
        echo "DB_NAME=${DB_NAME}" >> $GITHUB_ENV
        echo "ACR_REG_REPO_URL=${ACR_NAME}.azurecr.io/serviceprincipal" >> $GITHUB_ENV
        echo "STORAGE_NAME=${STORAGE_NAME}" >> $GITHUB_ENV

    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # needed to calulate patch

    - name: Run Unit Tests
      run: |
        cd src/Automation
        dotnet test --collect:"XPlat Code Coverage" --logger "console;verbosity=detailed" --filter "Category=Unit"

    - name: Create Testing Resources
      run: |
        export GIT_HASH=$( echo ${{ github.sha }} | cut -c1-7 )
        echo "GIT_HASH=${GIT_HASH}" >> $GITHUB_ENV
        export QUEUE_PREFIX="sit-$(date '+%Y%m%d')-${GIT_HASH}"
        echo "QUEUE_PREFIX=${QUEUE_PREFIX}" >> $GITHUB_ENV
        az storage queue create --fail-on-exist --account-name ${STORAGE_NAME} --name "${QUEUE_PREFIX}-discover"
        az storage queue create --fail-on-exist --account-name ${STORAGE_NAME} --name "${QUEUE_PREFIX}-evaluate"
        az storage queue create --fail-on-exist --account-name ${STORAGE_NAME} --name "${QUEUE_PREFIX}-update"
        cd src/Automation/CSE.Automation.TestsPrep
        export KEYVAULT_NAME="${KV_NAME}"
        dotnet run

    - name: Run Integration Tests
      continue-on-error: true
      run: |
        cd src/Automation
        export SPDiscoverQueue="${QUEUE_PREFIX}-discover"
        export SPEvaluateQueue="${QUEUE_PREFIX}-evaluate"
        export SPUpdateQueue="${QUEUE_PREFIX}-update"
        export KEYVAULT_NAME="${KV_NAME}"
        export SPCosmosURL="https://${DB_NAME}.documents.azure.com:443/"
        export SPCosmosDatabase=$(az cosmosdb sql database list -g $RESOURCE_GROUP -a $DB_NAME --query '[].name' -o tsv | grep qa)
        dotnet test --collect:"XPlat Code Coverage" --logger "console;verbosity=detailed" --filter "Category=Integration"

    - name: Cleanup Testing Resources
      if: ${{ always() }}
      run: |
        export temp_queues=$(az storage queue list --account-name ${STORAGE_NAME} --prefix ${QUEUE_PREFIX} -o tsv --query '[].name')
        for queue in $temp_queues; do
          az storage queue delete --account-name ${STORAGE_NAME} --name $queue
        done

    - name: Calculate Version
      run: |
        export version_from_config=$(git blame src/Automation/CSE.Automation/CSE.Automation.csproj | grep "</VersionPrefix>")
        export currenthash=$(git rev-parse HEAD)
        export lasthash=$(echo ${version_from_config} | awk '{print $1}')
        export patch=$(git log ${lasthash}..${currenthash} --pretty=oneline | wc -l | sed "s/\s//g")
        export majorminor=$(echo $version_from_config | grep -oP '\d+(\.\d+)+')
        export VERSION_PREFIX=${majorminor}.${patch}
        echo $VERSION_PREFIX
        echo "VERSION_PREFIX=${VERSION_PREFIX}" >> $GITHUB_ENV

    - name: Build Container
    # Version Prefix must be of following format: ^\d+(\.\d+){1,3}$
    # Version Suffix must be of following format: ^[0-9A-Za-z-]*$
      run: |
        if [[ "${{ github.event_name }}" == "push" ]]
        then
          VERSION_SUFFIX="${GIT_HASH}"
        else
          PR_NUMBER=$(echo "${{ github.ref }}" | awk 'BEGIN { FS = "/" } ; { print $3 }')
          VERSION_SUFFIX="PR${PR_NUMBER}-${GIT_HASH}"
        fi
        # Build Image
        docker build --pull -t temp \
                    --build-arg VERSION_PREFIX="${VERSION_PREFIX}" \
                    --build-arg VERSION_SUFFIX="${VERSION_SUFFIX}" \
                    -f src/Automation/CSE.Automation/Dockerfile src/Automation
    
    - name: Registry Login
    # do not copy the actual secrets
    # do not echo secrets
    # You must add the following secrets to github repo
    #    SERVICE_PRINCIPAL_ID     - ServicePrincipal Application ID
    #    SERVICE_PRINCIPAL_SECRET - Access Secret for the ServicePrincipal
      run: |
        # Login to Azure registry
        echo "${{ secrets.SERVICE_PRINCIPAL_SECRET }}" | docker login "${ACR_REG_REPO_URL}" -u ${{ secrets.SERVICE_PRINCIPAL_ID }} --password-stdin

    - name: Publish Container
      run: |
        if [[ "${{ github.event_name }}" == "push" ]]
        then
          VERSION_SUFFIX="${GIT_HASH}"
          docker tag temp ${ACR_REG_REPO_URL}:latest
        else
          PR_NUMBER=$(echo "${{ github.ref }}" | awk 'BEGIN { FS = "/" } ; { print $3 }')
          VERSION_SUFFIX="PR${PR_NUMBER}-${GIT_HASH}"
        fi
        
        SEMANTIC_VERSION="${VERSION_PREFIX}-${VERSION_SUFFIX}"

        IMAGE_NAME="${ACR_REG_REPO_URL}:${SEMANTIC_VERSION}"
        echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV

        docker tag temp "${IMAGE_NAME}"
        docker push ${ACR_REG_REPO_URL}

    - name: Deploy Application Settings 
      run: |        
        if [[ "${{ github.event_name }}" == "push" ]]
        then        
          .github/workflows/appConfigSettings.sh prod
        elif [[ "${{ github.event_name }}" == "pull_request" ]]
        then          
          
          echo "Setting STAGING docker image to ${IMAGE_NAME}"

          az functionapp config container set -g ${RESOURCE_GROUP} -n ${FN_NAME} --slot staging --docker-custom-image-name $IMAGE_NAME > /dev/null 2>&1
          az functionapp config appsettings set -g ${RESOURCE_GROUP} -n ${FN_NAME} --slot staging --settings "DOCKER_CUSTOM_IMAGE_NAME=${IMAGE_NAME}" > /dev/null 2>&1

          .github/workflows/appConfigSettings.sh qa
        fi

    - name: Tag Release
      if: github.event_name == 'push'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION_PREFIX }}
        release_name: ${{ env.VERSION_PREFIX }}
