name: Docker CI

on:
  push:
    branches:
      - main

    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'spikes/**' # Don't build the spikes unless explicitly specified

    tags:
      - v*
  
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
      - main

    paths-ignore:
    - 'docs/**'
    - '**.md'
    - 'spikes/**' # Don't build the spikes unless explicitly specified

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      ACR_REG_REPO_URL : serviceprincipalacrdev.azurecr.io/serviceprincipal

    steps:
    - name: Azure Login
      run: |
        # login to Azure
        az login --service-principal -u ${{ secrets.SERVICE_PRINCIPAL_ID }} --tenant ${{ secrets.TENANT_ID }} -p ${{ secrets.SERVICE_PRINCIPAL_SECRET }}    

    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # needed to calulate patch

    - name: Run Unit Tests
      run: |
        cd src/Automation
        dotnet test /p:CollectCoverage=true /p:CoverletOutput="./TestResults/"

    - name: Calculate Version
      run: |
        export version_from_config=$(git blame src/Automation/CSE.Automation/CSE.Automation.csproj | grep "</VersionPrefix>")
        export currenthash=$(git rev-parse HEAD)
        export lasthash=$(echo ${version_from_config} | awk '{print $1}')
        export patch=$(git log ${lasthash}..${currenthash} --pretty=oneline | wc -l | sed "s/\s//g")
        export majorminor=$(echo $version_from_config | grep -oP '\d+(\.\d+)+')
        export VERSION_PREFIX=${majorminor}.${patch}
        echo $VERSION_PREFIX
        echo "VERSION_PREFIX=${VERSION_PREFIX}" >> $GITHUB_ENV

    - name: Build Container
    # Version Prefix must be of following format: ^\d+(\.\d+){1,3}$
    # Version Suffix must be of following format: ^[0-9A-Za-z-]*$
      run: |
        GIT_HASH=$( echo ${{ github.sha }} | cut -c1-7 )
        if [[ "${{ github.event_name }}" == "push" ]]
        then
          VERSION_SUFFIX="${GIT_HASH}"
        else
          PR_NUMBER=$(echo "${{ github.ref }}" | awk 'BEGIN { FS = "/" } ; { print $3 }')
          VERSION_SUFFIX="PR${PR_NUMBER}-${GIT_HASH}"
        fi
        # Build Image
        docker build --pull -t temp \
                    --build-arg VERSION_PREFIX="${VERSION_PREFIX}" \
                    --build-arg VERSION_SUFFIX="${VERSION_SUFFIX}" \
                    -f src/Automation/CSE.Automation/Dockerfile src/Automation
    
    - name: Registry Login
    # do not copy the actual secrets
    # do not echo secrets
    # You must add the following secrets to github repo
    #    SERVICE_PRINCIPAL_ID     - ServicePrincipal Application ID
    #    SERVICE_PRINCIPAL_SECRET - Access Secret for the ServicePrincipal
      run: |
        # Login to Azure registry
        echo "${{ secrets.SERVICE_PRINCIPAL_SECRET }}" | docker login "${ACR_REG_REPO_URL}" -u ${{ secrets.SERVICE_PRINCIPAL_ID }} --password-stdin

    - name: Publish Container
      run: |
        export GIT_HASH=$( echo ${{ github.sha }} | cut -c1-7 )
        if [[ "${{ github.event_name }}" == "push" ]]
        then
          VERSION_SUFFIX="${GIT_HASH}"
          docker tag temp ${ACR_REG_REPO_URL}:latest
        else
          PR_NUMBER=$(echo "${{ github.ref }}" | awk 'BEGIN { FS = "/" } ; { print $3 }')
          VERSION_SUFFIX="PR${PR_NUMBER}-${GIT_HASH}"
        fi
        SEMANTIC_VERSION="${VERSION_PREFIX}-${VERSION_SUFFIX}"
        docker tag temp "${ACR_REG_REPO_URL}:${SEMANTIC_VERSION}"
        docker push ${ACR_REG_REPO_URL}

    - name: Deploy Application Settings 
      run: |        
        if [[ "${{ github.event_name }}" == "push" ]]
        then
          az functionapp config container set -g serviceprincipal-rg-dev -n sp-funcn-dev --docker-custom-image-name "${ACR_REG_REPO_URL}:latest"
          .github/workflows/appConfigSettings.sh prod
        elif [[ "${{ github.event_name }}" == "pull_request" ]]
        then
          az functionapp config container set -g serviceprincipal-rg-dev -n sp-funcn-dev --slot staging --docker-custom-image-name "${ACR_REG_REPO_URL}:${SEMANTIC_VERSION}"
          .github/workflows/appConfigSettings.sh qa
        fi

    - name: Run System Tests
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]
        then
          echo "RUN SYSTEM TESTS HERE"
        fi

    - name: Tag Release
      if: github.event_name == 'push'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION_PREFIX }}
        release_name: ${{ env.VERSION_PREFIX }}
