name: Docker CI

on:
  push:
    branches:
      - dummy-main

    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'spikes/**' # Don't build the spikes unless explicitly specified

    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ACR_REG_REPO_URL : serviceprincipalacrdev.azurecr.io/serviceprincipal
      # These are used in if: conditions
      ACR_LOGGED_IN    : false
      DKR_IMG_IS_BUILT : false
      TEMP_IMG_NAME    : sp_image

    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: dotnet tool install -g dotnet-version-cli
    - name: Bump Patch Version
      run: dotnet version patch
    - name: Sync Version Back To main
      run: git add . && git commit -m "bump version" && git push origin dummy-main
