name: Lint Check
on: 
  pull_request:
    types: [ opened, reopened, synchronize, closed ]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: dotnet tool install -g dotnet-format
    - name: Run dotnet-format
      run: |
        dotnet-format src/Automation/CSE.Automation --folder --check
